// Auto-generated by scripts/fetch-spdx.ts — do not edit manually
import _LX_0BSD from "./0BSD.json"
import _LX_3D_Slicer_1_0 from "./3D-Slicer-1.0.json"
import _LX_AAL from "./AAL.json"
import _LX_Abstyles from "./Abstyles.json"
import _LX_AdaCore_doc from "./AdaCore-doc.json"
import _LX_Adobe_2006 from "./Adobe-2006.json"
import _LX_Adobe_Display_PostScript from "./Adobe-Display-PostScript.json"
import _LX_Adobe_Glyph from "./Adobe-Glyph.json"
import _LX_Adobe_Utopia from "./Adobe-Utopia.json"
import _LX_ADSL from "./ADSL.json"
import _LX_Advanced_Cryptics_Dictionary from "./Advanced-Cryptics-Dictionary.json"
import _LX_AFL_1_1 from "./AFL-1.1.json"
import _LX_AFL_1_2 from "./AFL-1.2.json"
import _LX_AFL_2_0 from "./AFL-2.0.json"
import _LX_AFL_2_1 from "./AFL-2.1.json"
import _LX_AFL_3_0 from "./AFL-3.0.json"
import _LX_Afmparse from "./Afmparse.json"
import _LX_AGPL_1_0_only from "./AGPL-1.0-only.json"
import _LX_AGPL_1_0_or_later from "./AGPL-1.0-or-later.json"
import _LX_AGPL_3_0_only from "./AGPL-3.0-only.json"
import _LX_AGPL_3_0_or_later from "./AGPL-3.0-or-later.json"
import _LX_Aladdin from "./Aladdin.json"
import _LX_ALGLIB_Documentation from "./ALGLIB-Documentation.json"
import _LX_AMD_newlib from "./AMD-newlib.json"
import _LX_AMDPLPA from "./AMDPLPA.json"
import _LX_AML from "./AML.json"
import _LX_AML_glslang from "./AML-glslang.json"
import _LX_AMPAS from "./AMPAS.json"
import _LX_ANTLR_PD from "./ANTLR-PD.json"
import _LX_ANTLR_PD_fallback from "./ANTLR-PD-fallback.json"
import _LX_any_OSI from "./any-OSI.json"
import _LX_any_OSI_perl_modules from "./any-OSI-perl-modules.json"
import _LX_Apache_1_0 from "./Apache-1.0.json"
import _LX_Apache_1_1 from "./Apache-1.1.json"
import _LX_Apache_2_0 from "./Apache-2.0.json"
import _LX_APAFML from "./APAFML.json"
import _LX_APL_1_0 from "./APL-1.0.json"
import _LX_App_s2p from "./App-s2p.json"
import _LX_APSL_1_0 from "./APSL-1.0.json"
import _LX_APSL_1_1 from "./APSL-1.1.json"
import _LX_APSL_1_2 from "./APSL-1.2.json"
import _LX_APSL_2_0 from "./APSL-2.0.json"
import _LX_Arphic_1999 from "./Arphic-1999.json"
import _LX_Artistic_1_0 from "./Artistic-1.0.json"
import _LX_Artistic_1_0_cl8 from "./Artistic-1.0-cl8.json"
import _LX_Artistic_1_0_Perl from "./Artistic-1.0-Perl.json"
import _LX_Artistic_2_0 from "./Artistic-2.0.json"
import _LX_Artistic_dist from "./Artistic-dist.json"
import _LX_Aspell_RU from "./Aspell-RU.json"
import _LX_ASWF_Digital_Assets_1_0 from "./ASWF-Digital-Assets-1.0.json"
import _LX_ASWF_Digital_Assets_1_1 from "./ASWF-Digital-Assets-1.1.json"
import _LX_Baekmuk from "./Baekmuk.json"
import _LX_Bahyph from "./Bahyph.json"
import _LX_Barr from "./Barr.json"
import _LX_bcrypt_Solar_Designer from "./bcrypt-Solar-Designer.json"
import _LX_Beerware from "./Beerware.json"
import _LX_Bitstream_Charter from "./Bitstream-Charter.json"
import _LX_Bitstream_Vera from "./Bitstream-Vera.json"
import _LX_BitTorrent_1_0 from "./BitTorrent-1.0.json"
import _LX_BitTorrent_1_1 from "./BitTorrent-1.1.json"
import _LX_blessing from "./blessing.json"
import _LX_BlueOak_1_0_0 from "./BlueOak-1.0.0.json"
import _LX_Boehm_GC from "./Boehm-GC.json"
import _LX_Boehm_GC_without_fee from "./Boehm-GC-without-fee.json"
import _LX_BOLA_1_1 from "./BOLA-1.1.json"
import _LX_Borceux from "./Borceux.json"
import _LX_Brian_Gladman_2_Clause from "./Brian-Gladman-2-Clause.json"
import _LX_Brian_Gladman_3_Clause from "./Brian-Gladman-3-Clause.json"
import _LX_Brian_Gladman_3_Clause_no_conversion from "./Brian-Gladman-3-Clause-no-conversion.json"
import _LX_BSD_1_Clause from "./BSD-1-Clause.json"
import _LX_BSD_2_Clause from "./BSD-2-Clause.json"
import _LX_BSD_2_Clause_Darwin from "./BSD-2-Clause-Darwin.json"
import _LX_BSD_2_Clause_first_lines from "./BSD-2-Clause-first-lines.json"
import _LX_BSD_2_Clause_Patent from "./BSD-2-Clause-Patent.json"
import _LX_BSD_2_Clause_pkgconf_disclaimer from "./BSD-2-Clause-pkgconf-disclaimer.json"
import _LX_BSD_2_Clause_Views from "./BSD-2-Clause-Views.json"
import _LX_BSD_3_Clause from "./BSD-3-Clause.json"
import _LX_BSD_3_Clause_acpica from "./BSD-3-Clause-acpica.json"
import _LX_BSD_3_Clause_Attribution from "./BSD-3-Clause-Attribution.json"
import _LX_BSD_3_Clause_Clear from "./BSD-3-Clause-Clear.json"
import _LX_BSD_3_Clause_flex from "./BSD-3-Clause-flex.json"
import _LX_BSD_3_Clause_HP from "./BSD-3-Clause-HP.json"
import _LX_BSD_3_Clause_LBNL from "./BSD-3-Clause-LBNL.json"
import _LX_BSD_3_Clause_Modification from "./BSD-3-Clause-Modification.json"
import _LX_BSD_3_Clause_No_Military_License from "./BSD-3-Clause-No-Military-License.json"
import _LX_BSD_3_Clause_No_Nuclear_License from "./BSD-3-Clause-No-Nuclear-License.json"
import _LX_BSD_3_Clause_No_Nuclear_License_2014 from "./BSD-3-Clause-No-Nuclear-License-2014.json"
import _LX_BSD_3_Clause_No_Nuclear_Warranty from "./BSD-3-Clause-No-Nuclear-Warranty.json"
import _LX_BSD_3_Clause_Open_MPI from "./BSD-3-Clause-Open-MPI.json"
import _LX_BSD_3_Clause_Sun from "./BSD-3-Clause-Sun.json"
import _LX_BSD_3_Clause_Tso from "./BSD-3-Clause-Tso.json"
import _LX_BSD_4_Clause from "./BSD-4-Clause.json"
import _LX_BSD_4_Clause_Shortened from "./BSD-4-Clause-Shortened.json"
import _LX_BSD_4_Clause_UC from "./BSD-4-Clause-UC.json"
import _LX_BSD_4_3RENO from "./BSD-4.3RENO.json"
import _LX_BSD_4_3TAHOE from "./BSD-4.3TAHOE.json"
import _LX_BSD_Advertising_Acknowledgement from "./BSD-Advertising-Acknowledgement.json"
import _LX_BSD_Attribution_HPND_disclaimer from "./BSD-Attribution-HPND-disclaimer.json"
import _LX_BSD_Inferno_Nettverk from "./BSD-Inferno-Nettverk.json"
import _LX_BSD_Mark_Modifications from "./BSD-Mark-Modifications.json"
import _LX_BSD_Protection from "./BSD-Protection.json"
import _LX_BSD_Source_beginning_file from "./BSD-Source-beginning-file.json"
import _LX_BSD_Source_Code from "./BSD-Source-Code.json"
import _LX_BSD_Systemics from "./BSD-Systemics.json"
import _LX_BSD_Systemics_W3Works from "./BSD-Systemics-W3Works.json"
import _LX_BSL_1_0 from "./BSL-1.0.json"
import _LX_Buddy from "./Buddy.json"
import _LX_BUSL_1_1 from "./BUSL-1.1.json"
import _LX_bzip2_1_0_6 from "./bzip2-1.0.6.json"
import _LX_C_UDA_1_0 from "./C-UDA-1.0.json"
import _LX_CAL_1_0 from "./CAL-1.0.json"
import _LX_CAL_1_0_Combined_Work_Exception from "./CAL-1.0-Combined-Work-Exception.json"
import _LX_Caldera from "./Caldera.json"
import _LX_Caldera_no_preamble from "./Caldera-no-preamble.json"
import _LX_CAPEC_tou from "./CAPEC-tou.json"
import _LX_Catharon from "./Catharon.json"
import _LX_CATOSL_1_1 from "./CATOSL-1.1.json"
import _LX_CC_BY_1_0 from "./CC-BY-1.0.json"
import _LX_CC_BY_2_0 from "./CC-BY-2.0.json"
import _LX_CC_BY_2_5 from "./CC-BY-2.5.json"
import _LX_CC_BY_2_5_AU from "./CC-BY-2.5-AU.json"
import _LX_CC_BY_3_0 from "./CC-BY-3.0.json"
import _LX_CC_BY_3_0_AT from "./CC-BY-3.0-AT.json"
import _LX_CC_BY_3_0_AU from "./CC-BY-3.0-AU.json"
import _LX_CC_BY_3_0_DE from "./CC-BY-3.0-DE.json"
import _LX_CC_BY_3_0_IGO from "./CC-BY-3.0-IGO.json"
import _LX_CC_BY_3_0_NL from "./CC-BY-3.0-NL.json"
import _LX_CC_BY_3_0_US from "./CC-BY-3.0-US.json"
import _LX_CC_BY_4_0 from "./CC-BY-4.0.json"
import _LX_CC_BY_NC_1_0 from "./CC-BY-NC-1.0.json"
import _LX_CC_BY_NC_2_0 from "./CC-BY-NC-2.0.json"
import _LX_CC_BY_NC_2_5 from "./CC-BY-NC-2.5.json"
import _LX_CC_BY_NC_3_0 from "./CC-BY-NC-3.0.json"
import _LX_CC_BY_NC_3_0_DE from "./CC-BY-NC-3.0-DE.json"
import _LX_CC_BY_NC_4_0 from "./CC-BY-NC-4.0.json"
import _LX_CC_BY_NC_ND_1_0 from "./CC-BY-NC-ND-1.0.json"
import _LX_CC_BY_NC_ND_2_0 from "./CC-BY-NC-ND-2.0.json"
import _LX_CC_BY_NC_ND_2_5 from "./CC-BY-NC-ND-2.5.json"
import _LX_CC_BY_NC_ND_3_0 from "./CC-BY-NC-ND-3.0.json"
import _LX_CC_BY_NC_ND_3_0_DE from "./CC-BY-NC-ND-3.0-DE.json"
import _LX_CC_BY_NC_ND_3_0_IGO from "./CC-BY-NC-ND-3.0-IGO.json"
import _LX_CC_BY_NC_ND_4_0 from "./CC-BY-NC-ND-4.0.json"
import _LX_CC_BY_NC_SA_1_0 from "./CC-BY-NC-SA-1.0.json"
import _LX_CC_BY_NC_SA_2_0 from "./CC-BY-NC-SA-2.0.json"
import _LX_CC_BY_NC_SA_2_0_DE from "./CC-BY-NC-SA-2.0-DE.json"
import _LX_CC_BY_NC_SA_2_0_FR from "./CC-BY-NC-SA-2.0-FR.json"
import _LX_CC_BY_NC_SA_2_0_UK from "./CC-BY-NC-SA-2.0-UK.json"
import _LX_CC_BY_NC_SA_2_5 from "./CC-BY-NC-SA-2.5.json"
import _LX_CC_BY_NC_SA_3_0 from "./CC-BY-NC-SA-3.0.json"
import _LX_CC_BY_NC_SA_3_0_DE from "./CC-BY-NC-SA-3.0-DE.json"
import _LX_CC_BY_NC_SA_3_0_IGO from "./CC-BY-NC-SA-3.0-IGO.json"
import _LX_CC_BY_NC_SA_4_0 from "./CC-BY-NC-SA-4.0.json"
import _LX_CC_BY_ND_1_0 from "./CC-BY-ND-1.0.json"
import _LX_CC_BY_ND_2_0 from "./CC-BY-ND-2.0.json"
import _LX_CC_BY_ND_2_5 from "./CC-BY-ND-2.5.json"
import _LX_CC_BY_ND_3_0 from "./CC-BY-ND-3.0.json"
import _LX_CC_BY_ND_3_0_DE from "./CC-BY-ND-3.0-DE.json"
import _LX_CC_BY_ND_4_0 from "./CC-BY-ND-4.0.json"
import _LX_CC_BY_SA_1_0 from "./CC-BY-SA-1.0.json"
import _LX_CC_BY_SA_2_0 from "./CC-BY-SA-2.0.json"
import _LX_CC_BY_SA_2_0_UK from "./CC-BY-SA-2.0-UK.json"
import _LX_CC_BY_SA_2_1_JP from "./CC-BY-SA-2.1-JP.json"
import _LX_CC_BY_SA_2_5 from "./CC-BY-SA-2.5.json"
import _LX_CC_BY_SA_3_0 from "./CC-BY-SA-3.0.json"
import _LX_CC_BY_SA_3_0_AT from "./CC-BY-SA-3.0-AT.json"
import _LX_CC_BY_SA_3_0_DE from "./CC-BY-SA-3.0-DE.json"
import _LX_CC_BY_SA_3_0_IGO from "./CC-BY-SA-3.0-IGO.json"
import _LX_CC_BY_SA_4_0 from "./CC-BY-SA-4.0.json"
import _LX_CC_PDDC from "./CC-PDDC.json"
import _LX_CC_PDM_1_0 from "./CC-PDM-1.0.json"
import _LX_CC_SA_1_0 from "./CC-SA-1.0.json"
import _LX_CC0_1_0 from "./CC0-1.0.json"
import _LX_CDDL_1_0 from "./CDDL-1.0.json"
import _LX_CDDL_1_1 from "./CDDL-1.1.json"
import _LX_CDL_1_0 from "./CDL-1.0.json"
import _LX_CDLA_Permissive_1_0 from "./CDLA-Permissive-1.0.json"
import _LX_CDLA_Permissive_2_0 from "./CDLA-Permissive-2.0.json"
import _LX_CDLA_Sharing_1_0 from "./CDLA-Sharing-1.0.json"
import _LX_CECILL_1_0 from "./CECILL-1.0.json"
import _LX_CECILL_1_1 from "./CECILL-1.1.json"
import _LX_CECILL_2_0 from "./CECILL-2.0.json"
import _LX_CECILL_2_1 from "./CECILL-2.1.json"
import _LX_CECILL_B from "./CECILL-B.json"
import _LX_CECILL_C from "./CECILL-C.json"
import _LX_CERN_OHL_1_1 from "./CERN-OHL-1.1.json"
import _LX_CERN_OHL_1_2 from "./CERN-OHL-1.2.json"
import _LX_CERN_OHL_P_2_0 from "./CERN-OHL-P-2.0.json"
import _LX_CERN_OHL_S_2_0 from "./CERN-OHL-S-2.0.json"
import _LX_CERN_OHL_W_2_0 from "./CERN-OHL-W-2.0.json"
import _LX_CFITSIO from "./CFITSIO.json"
import _LX_check_cvs from "./check-cvs.json"
import _LX_checkmk from "./checkmk.json"
import _LX_ClArtistic from "./ClArtistic.json"
import _LX_Clips from "./Clips.json"
import _LX_CMU_Mach from "./CMU-Mach.json"
import _LX_CMU_Mach_nodoc from "./CMU-Mach-nodoc.json"
import _LX_CNRI_Jython from "./CNRI-Jython.json"
import _LX_CNRI_Python from "./CNRI-Python.json"
import _LX_CNRI_Python_GPL_Compatible from "./CNRI-Python-GPL-Compatible.json"
import _LX_COIL_1_0 from "./COIL-1.0.json"
import _LX_Community_Spec_1_0 from "./Community-Spec-1.0.json"
import _LX_Condor_1_1 from "./Condor-1.1.json"
import _LX_copyleft_next_0_3_0 from "./copyleft-next-0.3.0.json"
import _LX_copyleft_next_0_3_1 from "./copyleft-next-0.3.1.json"
import _LX_Cornell_Lossless_JPEG from "./Cornell-Lossless-JPEG.json"
import _LX_CPAL_1_0 from "./CPAL-1.0.json"
import _LX_CPL_1_0 from "./CPL-1.0.json"
import _LX_CPOL_1_02 from "./CPOL-1.02.json"
import _LX_Cronyx from "./Cronyx.json"
import _LX_Crossword from "./Crossword.json"
import _LX_CryptoSwift from "./CryptoSwift.json"
import _LX_CrystalStacker from "./CrystalStacker.json"
import _LX_CUA_OPL_1_0 from "./CUA-OPL-1.0.json"
import _LX_Cube from "./Cube.json"
import _LX_curl from "./curl.json"
import _LX_cve_tou from "./cve-tou.json"
import _LX_D_FSL_1_0 from "./D-FSL-1.0.json"
import _LX_DEC_3_Clause from "./DEC-3-Clause.json"
import _LX_diffmark from "./diffmark.json"
import _LX_DL_DE_BY_2_0 from "./DL-DE-BY-2.0.json"
import _LX_DL_DE_ZERO_2_0 from "./DL-DE-ZERO-2.0.json"
import _LX_DOC from "./DOC.json"
import _LX_DocBook_DTD from "./DocBook-DTD.json"
import _LX_DocBook_Schema from "./DocBook-Schema.json"
import _LX_DocBook_Stylesheet from "./DocBook-Stylesheet.json"
import _LX_DocBook_XML from "./DocBook-XML.json"
import _LX_Dotseqn from "./Dotseqn.json"
import _LX_DRL_1_0 from "./DRL-1.0.json"
import _LX_DRL_1_1 from "./DRL-1.1.json"
import _LX_DSDP from "./DSDP.json"
import _LX_dtoa from "./dtoa.json"
import _LX_dvipdfm from "./dvipdfm.json"
import _LX_ECL_1_0 from "./ECL-1.0.json"
import _LX_ECL_2_0 from "./ECL-2.0.json"
import _LX_EFL_1_0 from "./EFL-1.0.json"
import _LX_EFL_2_0 from "./EFL-2.0.json"
import _LX_eGenix from "./eGenix.json"
import _LX_Elastic_2_0 from "./Elastic-2.0.json"
import _LX_Entessa from "./Entessa.json"
import _LX_EPICS from "./EPICS.json"
import _LX_EPL_1_0 from "./EPL-1.0.json"
import _LX_EPL_2_0 from "./EPL-2.0.json"
import _LX_ErlPL_1_1 from "./ErlPL-1.1.json"
import _LX_ESA_PL_permissive_2_4 from "./ESA-PL-permissive-2.4.json"
import _LX_ESA_PL_strong_copyleft_2_4 from "./ESA-PL-strong-copyleft-2.4.json"
import _LX_ESA_PL_weak_copyleft_2_4 from "./ESA-PL-weak-copyleft-2.4.json"
import _LX_etalab_2_0 from "./etalab-2.0.json"
import _LX_EUDatagrid from "./EUDatagrid.json"
import _LX_EUPL_1_0 from "./EUPL-1.0.json"
import _LX_EUPL_1_1 from "./EUPL-1.1.json"
import _LX_EUPL_1_2 from "./EUPL-1.2.json"
import _LX_Eurosym from "./Eurosym.json"
import _LX_Fair from "./Fair.json"
import _LX_FBM from "./FBM.json"
import _LX_FDK_AAC from "./FDK-AAC.json"
import _LX_Ferguson_Twofish from "./Ferguson-Twofish.json"
import _LX_Frameworx_1_0 from "./Frameworx-1.0.json"
import _LX_FreeBSD_DOC from "./FreeBSD-DOC.json"
import _LX_FreeImage from "./FreeImage.json"
import _LX_FSFAP from "./FSFAP.json"
import _LX_FSFAP_no_warranty_disclaimer from "./FSFAP-no-warranty-disclaimer.json"
import _LX_FSFUL from "./FSFUL.json"
import _LX_FSFULLR from "./FSFULLR.json"
import _LX_FSFULLRSD from "./FSFULLRSD.json"
import _LX_FSFULLRWD from "./FSFULLRWD.json"
import _LX_FSL_1_1_ALv2 from "./FSL-1.1-ALv2.json"
import _LX_FSL_1_1_MIT from "./FSL-1.1-MIT.json"
import _LX_FTL from "./FTL.json"
import _LX_Furuseth from "./Furuseth.json"
import _LX_fwlw from "./fwlw.json"
import _LX_Game_Programming_Gems from "./Game-Programming-Gems.json"
import _LX_GCR_docs from "./GCR-docs.json"
import _LX_GD from "./GD.json"
import _LX_generic_xts from "./generic-xts.json"
import _LX_GFDL_1_1_invariants_only from "./GFDL-1.1-invariants-only.json"
import _LX_GFDL_1_1_invariants_or_later from "./GFDL-1.1-invariants-or-later.json"
import _LX_GFDL_1_1_no_invariants_only from "./GFDL-1.1-no-invariants-only.json"
import _LX_GFDL_1_1_no_invariants_or_later from "./GFDL-1.1-no-invariants-or-later.json"
import _LX_GFDL_1_1_only from "./GFDL-1.1-only.json"
import _LX_GFDL_1_1_or_later from "./GFDL-1.1-or-later.json"
import _LX_GFDL_1_2_invariants_only from "./GFDL-1.2-invariants-only.json"
import _LX_GFDL_1_2_invariants_or_later from "./GFDL-1.2-invariants-or-later.json"
import _LX_GFDL_1_2_no_invariants_only from "./GFDL-1.2-no-invariants-only.json"
import _LX_GFDL_1_2_no_invariants_or_later from "./GFDL-1.2-no-invariants-or-later.json"
import _LX_GFDL_1_2_only from "./GFDL-1.2-only.json"
import _LX_GFDL_1_2_or_later from "./GFDL-1.2-or-later.json"
import _LX_GFDL_1_3_invariants_only from "./GFDL-1.3-invariants-only.json"
import _LX_GFDL_1_3_invariants_or_later from "./GFDL-1.3-invariants-or-later.json"
import _LX_GFDL_1_3_no_invariants_only from "./GFDL-1.3-no-invariants-only.json"
import _LX_GFDL_1_3_no_invariants_or_later from "./GFDL-1.3-no-invariants-or-later.json"
import _LX_GFDL_1_3_only from "./GFDL-1.3-only.json"
import _LX_GFDL_1_3_or_later from "./GFDL-1.3-or-later.json"
import _LX_Giftware from "./Giftware.json"
import _LX_GL2PS from "./GL2PS.json"
import _LX_Glide from "./Glide.json"
import _LX_Glulxe from "./Glulxe.json"
import _LX_GLWTPL from "./GLWTPL.json"
import _LX_gnuplot from "./gnuplot.json"
import _LX_GPL_1_0_only from "./GPL-1.0-only.json"
import _LX_GPL_1_0_or_later from "./GPL-1.0-or-later.json"
import _LX_GPL_2_0_only from "./GPL-2.0-only.json"
import _LX_GPL_2_0_or_later from "./GPL-2.0-or-later.json"
import _LX_GPL_3_0_only from "./GPL-3.0-only.json"
import _LX_GPL_3_0_or_later from "./GPL-3.0-or-later.json"
import _LX_Graphics_Gems from "./Graphics-Gems.json"
import _LX_gSOAP_1_3b from "./gSOAP-1.3b.json"
import _LX_gtkbook from "./gtkbook.json"
import _LX_Gutmann from "./Gutmann.json"
import _LX_HaskellReport from "./HaskellReport.json"
import _LX_HDF5 from "./HDF5.json"
import _LX_hdparm from "./hdparm.json"
import _LX_HIDAPI from "./HIDAPI.json"
import _LX_Hippocratic_2_1 from "./Hippocratic-2.1.json"
import _LX_HP_1986 from "./HP-1986.json"
import _LX_HP_1989 from "./HP-1989.json"
import _LX_HPND from "./HPND.json"
import _LX_HPND_DEC from "./HPND-DEC.json"
import _LX_HPND_doc from "./HPND-doc.json"
import _LX_HPND_doc_sell from "./HPND-doc-sell.json"
import _LX_HPND_export_US from "./HPND-export-US.json"
import _LX_HPND_export_US_acknowledgement from "./HPND-export-US-acknowledgement.json"
import _LX_HPND_export_US_modify from "./HPND-export-US-modify.json"
import _LX_HPND_export2_US from "./HPND-export2-US.json"
import _LX_HPND_Fenneberg_Livingston from "./HPND-Fenneberg-Livingston.json"
import _LX_HPND_INRIA_IMAG from "./HPND-INRIA-IMAG.json"
import _LX_HPND_Intel from "./HPND-Intel.json"
import _LX_HPND_Kevlin_Henney from "./HPND-Kevlin-Henney.json"
import _LX_HPND_Markus_Kuhn from "./HPND-Markus-Kuhn.json"
import _LX_HPND_merchantability_variant from "./HPND-merchantability-variant.json"
import _LX_HPND_MIT_disclaimer from "./HPND-MIT-disclaimer.json"
import _LX_HPND_Netrek from "./HPND-Netrek.json"
import _LX_HPND_Pbmplus from "./HPND-Pbmplus.json"
import _LX_HPND_sell_MIT_disclaimer_xserver from "./HPND-sell-MIT-disclaimer-xserver.json"
import _LX_HPND_sell_regexpr from "./HPND-sell-regexpr.json"
import _LX_HPND_sell_variant from "./HPND-sell-variant.json"
import _LX_HPND_sell_variant_critical_systems from "./HPND-sell-variant-critical-systems.json"
import _LX_HPND_sell_variant_MIT_disclaimer from "./HPND-sell-variant-MIT-disclaimer.json"
import _LX_HPND_sell_variant_MIT_disclaimer_rev from "./HPND-sell-variant-MIT-disclaimer-rev.json"
import _LX_HPND_SMC from "./HPND-SMC.json"
import _LX_HPND_UC from "./HPND-UC.json"
import _LX_HPND_UC_export_US from "./HPND-UC-export-US.json"
import _LX_HTMLTIDY from "./HTMLTIDY.json"
import _LX_hyphen_bulgarian from "./hyphen-bulgarian.json"
import _LX_IBM_pibs from "./IBM-pibs.json"
import _LX_ICU from "./ICU.json"
import _LX_IEC_Code_Components_EULA from "./IEC-Code-Components-EULA.json"
import _LX_IJG from "./IJG.json"
import _LX_IJG_short from "./IJG-short.json"
import _LX_ImageMagick from "./ImageMagick.json"
import _LX_iMatix from "./iMatix.json"
import _LX_Imlib2 from "./Imlib2.json"
import _LX_Info_ZIP from "./Info-ZIP.json"
import _LX_Inner_Net_2_0 from "./Inner-Net-2.0.json"
import _LX_InnoSetup from "./InnoSetup.json"
import _LX_Intel from "./Intel.json"
import _LX_Intel_ACPI from "./Intel-ACPI.json"
import _LX_Interbase_1_0 from "./Interbase-1.0.json"
import _LX_IPA from "./IPA.json"
import _LX_IPL_1_0 from "./IPL-1.0.json"
import _LX_ISC from "./ISC.json"
import _LX_ISC_Veillard from "./ISC-Veillard.json"
import _LX_ISO_permission from "./ISO-permission.json"
import _LX_Jam from "./Jam.json"
import _LX_JasPer_2_0 from "./JasPer-2.0.json"
import _LX_jove from "./jove.json"
import _LX_JPL_image from "./JPL-image.json"
import _LX_JPNIC from "./JPNIC.json"
import _LX_JSON from "./JSON.json"
import _LX_Kastrup from "./Kastrup.json"
import _LX_Kazlib from "./Kazlib.json"
import _LX_Knuth_CTAN from "./Knuth-CTAN.json"
import _LX_LAL_1_2 from "./LAL-1.2.json"
import _LX_LAL_1_3 from "./LAL-1.3.json"
import _LX_Latex2e from "./Latex2e.json"
import _LX_Latex2e_translated_notice from "./Latex2e-translated-notice.json"
import _LX_Leptonica from "./Leptonica.json"
import _LX_LGPL_2_0_only from "./LGPL-2.0-only.json"
import _LX_LGPL_2_0_or_later from "./LGPL-2.0-or-later.json"
import _LX_LGPL_2_1_only from "./LGPL-2.1-only.json"
import _LX_LGPL_2_1_or_later from "./LGPL-2.1-or-later.json"
import _LX_LGPL_3_0_only from "./LGPL-3.0-only.json"
import _LX_LGPL_3_0_or_later from "./LGPL-3.0-or-later.json"
import _LX_LGPLLR from "./LGPLLR.json"
import _LX_Libpng from "./Libpng.json"
import _LX_libpng_1_6_35 from "./libpng-1.6.35.json"
import _LX_libpng_2_0 from "./libpng-2.0.json"
import _LX_libselinux_1_0 from "./libselinux-1.0.json"
import _LX_libtiff from "./libtiff.json"
import _LX_libutil_David_Nugent from "./libutil-David-Nugent.json"
import _LX_LiLiQ_P_1_1 from "./LiLiQ-P-1.1.json"
import _LX_LiLiQ_R_1_1 from "./LiLiQ-R-1.1.json"
import _LX_LiLiQ_Rplus_1_1 from "./LiLiQ-Rplus-1.1.json"
import _LX_Linux_man_pages_1_para from "./Linux-man-pages-1-para.json"
import _LX_Linux_man_pages_copyleft from "./Linux-man-pages-copyleft.json"
import _LX_Linux_man_pages_copyleft_2_para from "./Linux-man-pages-copyleft-2-para.json"
import _LX_Linux_man_pages_copyleft_var from "./Linux-man-pages-copyleft-var.json"
import _LX_Linux_OpenIB from "./Linux-OpenIB.json"
import _LX_LOOP from "./LOOP.json"
import _LX_LPD_document from "./LPD-document.json"
import _LX_LPL_1_0 from "./LPL-1.0.json"
import _LX_LPL_1_02 from "./LPL-1.02.json"
import _LX_LPPL_1_0 from "./LPPL-1.0.json"
import _LX_LPPL_1_1 from "./LPPL-1.1.json"
import _LX_LPPL_1_2 from "./LPPL-1.2.json"
import _LX_LPPL_1_3a from "./LPPL-1.3a.json"
import _LX_LPPL_1_3c from "./LPPL-1.3c.json"
import _LX_lsof from "./lsof.json"
import _LX_Lucida_Bitmap_Fonts from "./Lucida-Bitmap-Fonts.json"
import _LX_LZMA_SDK_9_11_to_9_20 from "./LZMA-SDK-9.11-to-9.20.json"
import _LX_LZMA_SDK_9_22 from "./LZMA-SDK-9.22.json"
import _LX_Mackerras_3_Clause from "./Mackerras-3-Clause.json"
import _LX_Mackerras_3_Clause_acknowledgment from "./Mackerras-3-Clause-acknowledgment.json"
import _LX_magaz from "./magaz.json"
import _LX_mailprio from "./mailprio.json"
import _LX_MakeIndex from "./MakeIndex.json"
import _LX_man2html from "./man2html.json"
import _LX_Martin_Birgmeier from "./Martin-Birgmeier.json"
import _LX_McPhee_slideshow from "./McPhee-slideshow.json"
import _LX_metamail from "./metamail.json"
import _LX_Minpack from "./Minpack.json"
import _LX_MIPS from "./MIPS.json"
import _LX_MirOS from "./MirOS.json"
import _LX_MIT from "./MIT.json"
import _LX_MIT_0 from "./MIT-0.json"
import _LX_MIT_advertising from "./MIT-advertising.json"
import _LX_MIT_Click from "./MIT-Click.json"
import _LX_MIT_CMU from "./MIT-CMU.json"
import _LX_MIT_enna from "./MIT-enna.json"
import _LX_MIT_feh from "./MIT-feh.json"
import _LX_MIT_Festival from "./MIT-Festival.json"
import _LX_MIT_Khronos_old from "./MIT-Khronos-old.json"
import _LX_MIT_Modern_Variant from "./MIT-Modern-Variant.json"
import _LX_MIT_open_group from "./MIT-open-group.json"
import _LX_MIT_STK from "./MIT-STK.json"
import _LX_MIT_testregex from "./MIT-testregex.json"
import _LX_MIT_Wu from "./MIT-Wu.json"
import _LX_MITNFA from "./MITNFA.json"
import _LX_MMIXware from "./MMIXware.json"
import _LX_MMPL_1_0_1 from "./MMPL-1.0.1.json"
import _LX_Motosoto from "./Motosoto.json"
import _LX_MPEG_SSG from "./MPEG-SSG.json"
import _LX_mpi_permissive from "./mpi-permissive.json"
import _LX_mpich2 from "./mpich2.json"
import _LX_MPL_1_0 from "./MPL-1.0.json"
import _LX_MPL_1_1 from "./MPL-1.1.json"
import _LX_MPL_2_0 from "./MPL-2.0.json"
import _LX_MPL_2_0_no_copyleft_exception from "./MPL-2.0-no-copyleft-exception.json"
import _LX_mplus from "./mplus.json"
import _LX_MS_LPL from "./MS-LPL.json"
import _LX_MS_PL from "./MS-PL.json"
import _LX_MS_RL from "./MS-RL.json"
import _LX_MTLL from "./MTLL.json"
import _LX_MulanPSL_1_0 from "./MulanPSL-1.0.json"
import _LX_MulanPSL_2_0 from "./MulanPSL-2.0.json"
import _LX_Multics from "./Multics.json"
import _LX_Mup from "./Mup.json"
import _LX_MVT_1_1 from "./MVT-1.1.json"
import _LX_NAIST_2003 from "./NAIST-2003.json"
import _LX_NASA_1_3 from "./NASA-1.3.json"
import _LX_Naumen from "./Naumen.json"
import _LX_NBPL_1_0 from "./NBPL-1.0.json"
import _LX_NCBI_PD from "./NCBI-PD.json"
import _LX_NCGL_UK_2_0 from "./NCGL-UK-2.0.json"
import _LX_NCL from "./NCL.json"
import _LX_NCSA from "./NCSA.json"
import _LX_NetCDF from "./NetCDF.json"
import _LX_Newsletr from "./Newsletr.json"
import _LX_NGPL from "./NGPL.json"
import _LX_ngrep from "./ngrep.json"
import _LX_NICTA_1_0 from "./NICTA-1.0.json"
import _LX_NIST_PD from "./NIST-PD.json"
import _LX_NIST_PD_fallback from "./NIST-PD-fallback.json"
import _LX_NIST_PD_TNT from "./NIST-PD-TNT.json"
import _LX_NIST_Software from "./NIST-Software.json"
import _LX_NLOD_1_0 from "./NLOD-1.0.json"
import _LX_NLOD_2_0 from "./NLOD-2.0.json"
import _LX_NLPL from "./NLPL.json"
import _LX_Nokia from "./Nokia.json"
import _LX_NOSL from "./NOSL.json"
import _LX_Noweb from "./Noweb.json"
import _LX_NPL_1_0 from "./NPL-1.0.json"
import _LX_NPL_1_1 from "./NPL-1.1.json"
import _LX_NPOSL_3_0 from "./NPOSL-3.0.json"
import _LX_NRL from "./NRL.json"
import _LX_NTIA_PD from "./NTIA-PD.json"
import _LX_NTP from "./NTP.json"
import _LX_NTP_0 from "./NTP-0.json"
import _LX_O_UDA_1_0 from "./O-UDA-1.0.json"
import _LX_OAR from "./OAR.json"
import _LX_OCCT_PL from "./OCCT-PL.json"
import _LX_OCLC_2_0 from "./OCLC-2.0.json"
import _LX_ODbL_1_0 from "./ODbL-1.0.json"
import _LX_ODC_By_1_0 from "./ODC-By-1.0.json"
import _LX_OFFIS from "./OFFIS.json"
import _LX_OFL_1_0 from "./OFL-1.0.json"
import _LX_OFL_1_0_no_RFN from "./OFL-1.0-no-RFN.json"
import _LX_OFL_1_0_RFN from "./OFL-1.0-RFN.json"
import _LX_OFL_1_1 from "./OFL-1.1.json"
import _LX_OFL_1_1_no_RFN from "./OFL-1.1-no-RFN.json"
import _LX_OFL_1_1_RFN from "./OFL-1.1-RFN.json"
import _LX_OGC_1_0 from "./OGC-1.0.json"
import _LX_OGDL_Taiwan_1_0 from "./OGDL-Taiwan-1.0.json"
import _LX_OGL_Canada_2_0 from "./OGL-Canada-2.0.json"
import _LX_OGL_UK_1_0 from "./OGL-UK-1.0.json"
import _LX_OGL_UK_2_0 from "./OGL-UK-2.0.json"
import _LX_OGL_UK_3_0 from "./OGL-UK-3.0.json"
import _LX_OGTSL from "./OGTSL.json"
import _LX_OLDAP_1_1 from "./OLDAP-1.1.json"
import _LX_OLDAP_1_2 from "./OLDAP-1.2.json"
import _LX_OLDAP_1_3 from "./OLDAP-1.3.json"
import _LX_OLDAP_1_4 from "./OLDAP-1.4.json"
import _LX_OLDAP_2_0 from "./OLDAP-2.0.json"
import _LX_OLDAP_2_0_1 from "./OLDAP-2.0.1.json"
import _LX_OLDAP_2_1 from "./OLDAP-2.1.json"
import _LX_OLDAP_2_2 from "./OLDAP-2.2.json"
import _LX_OLDAP_2_2_1 from "./OLDAP-2.2.1.json"
import _LX_OLDAP_2_2_2 from "./OLDAP-2.2.2.json"
import _LX_OLDAP_2_3 from "./OLDAP-2.3.json"
import _LX_OLDAP_2_4 from "./OLDAP-2.4.json"
import _LX_OLDAP_2_5 from "./OLDAP-2.5.json"
import _LX_OLDAP_2_6 from "./OLDAP-2.6.json"
import _LX_OLDAP_2_7 from "./OLDAP-2.7.json"
import _LX_OLDAP_2_8 from "./OLDAP-2.8.json"
import _LX_OLFL_1_3 from "./OLFL-1.3.json"
import _LX_OML from "./OML.json"
import _LX_OpenMDW_1_0 from "./OpenMDW-1.0.json"
import _LX_OpenPBS_2_3 from "./OpenPBS-2.3.json"
import _LX_OpenSSL from "./OpenSSL.json"
import _LX_OpenSSL_standalone from "./OpenSSL-standalone.json"
import _LX_OpenVision from "./OpenVision.json"
import _LX_OPL_1_0 from "./OPL-1.0.json"
import _LX_OPL_UK_3_0 from "./OPL-UK-3.0.json"
import _LX_OPUBL_1_0 from "./OPUBL-1.0.json"
import _LX_OSC_1_0 from "./OSC-1.0.json"
import _LX_OSET_PL_2_1 from "./OSET-PL-2.1.json"
import _LX_OSL_1_0 from "./OSL-1.0.json"
import _LX_OSL_1_1 from "./OSL-1.1.json"
import _LX_OSL_2_0 from "./OSL-2.0.json"
import _LX_OSL_2_1 from "./OSL-2.1.json"
import _LX_OSL_3_0 from "./OSL-3.0.json"
import _LX_OSSP from "./OSSP.json"
import _LX_PADL from "./PADL.json"
import _LX_ParaType_Free_Font_1_3 from "./ParaType-Free-Font-1.3.json"
import _LX_Parity_6_0_0 from "./Parity-6.0.0.json"
import _LX_Parity_7_0_0 from "./Parity-7.0.0.json"
import _LX_PDDL_1_0 from "./PDDL-1.0.json"
import _LX_PHP_3_0 from "./PHP-3.0.json"
import _LX_PHP_3_01 from "./PHP-3.01.json"
import _LX_Pixar from "./Pixar.json"
import _LX_pkgconf from "./pkgconf.json"
import _LX_Plexus from "./Plexus.json"
import _LX_pnmstitch from "./pnmstitch.json"
import _LX_PolyForm_Noncommercial_1_0_0 from "./PolyForm-Noncommercial-1.0.0.json"
import _LX_PolyForm_Small_Business_1_0_0 from "./PolyForm-Small-Business-1.0.0.json"
import _LX_PostgreSQL from "./PostgreSQL.json"
import _LX_PPL from "./PPL.json"
import _LX_PSF_2_0 from "./PSF-2.0.json"
import _LX_psfrag from "./psfrag.json"
import _LX_psutils from "./psutils.json"
import _LX_Python_2_0 from "./Python-2.0.json"
import _LX_Python_2_0_1 from "./Python-2.0.1.json"
import _LX_python_ldap from "./python-ldap.json"
import _LX_Qhull from "./Qhull.json"
import _LX_QPL_1_0 from "./QPL-1.0.json"
import _LX_QPL_1_0_INRIA_2004 from "./QPL-1.0-INRIA-2004.json"
import _LX_radvd from "./radvd.json"
import _LX_Rdisc from "./Rdisc.json"
import _LX_RHeCos_1_1 from "./RHeCos-1.1.json"
import _LX_RPL_1_1 from "./RPL-1.1.json"
import _LX_RPL_1_5 from "./RPL-1.5.json"
import _LX_RPSL_1_0 from "./RPSL-1.0.json"
import _LX_RSA_MD from "./RSA-MD.json"
import _LX_RSCPL from "./RSCPL.json"
import _LX_Ruby from "./Ruby.json"
import _LX_Ruby_pty from "./Ruby-pty.json"
import _LX_SAX_PD from "./SAX-PD.json"
import _LX_SAX_PD_2_0 from "./SAX-PD-2.0.json"
import _LX_Saxpath from "./Saxpath.json"
import _LX_SCEA from "./SCEA.json"
import _LX_SchemeReport from "./SchemeReport.json"
import _LX_Sendmail from "./Sendmail.json"
import _LX_Sendmail_8_23 from "./Sendmail-8.23.json"
import _LX_Sendmail_Open_Source_1_1 from "./Sendmail-Open-Source-1.1.json"
import _LX_SGI_B_1_0 from "./SGI-B-1.0.json"
import _LX_SGI_B_1_1 from "./SGI-B-1.1.json"
import _LX_SGI_B_2_0 from "./SGI-B-2.0.json"
import _LX_SGI_OpenGL from "./SGI-OpenGL.json"
import _LX_SGMLUG_PM from "./SGMLUG-PM.json"
import _LX_SGP4 from "./SGP4.json"
import _LX_SHL_0_5 from "./SHL-0.5.json"
import _LX_SHL_0_51 from "./SHL-0.51.json"
import _LX_SimPL_2_0 from "./SimPL-2.0.json"
import _LX_SISSL from "./SISSL.json"
import _LX_SISSL_1_2 from "./SISSL-1.2.json"
import _LX_SL from "./SL.json"
import _LX_Sleepycat from "./Sleepycat.json"
import _LX_SMAIL_GPL from "./SMAIL-GPL.json"
import _LX_SMLNJ from "./SMLNJ.json"
import _LX_SMPPL from "./SMPPL.json"
import _LX_SNIA from "./SNIA.json"
import _LX_snprintf from "./snprintf.json"
import _LX_SOFA from "./SOFA.json"
import _LX_softSurfer from "./softSurfer.json"
import _LX_Soundex from "./Soundex.json"
import _LX_Spencer_86 from "./Spencer-86.json"
import _LX_Spencer_94 from "./Spencer-94.json"
import _LX_Spencer_99 from "./Spencer-99.json"
import _LX_SPL_1_0 from "./SPL-1.0.json"
import _LX_ssh_keyscan from "./ssh-keyscan.json"
import _LX_SSH_OpenSSH from "./SSH-OpenSSH.json"
import _LX_SSH_short from "./SSH-short.json"
import _LX_SSLeay_standalone from "./SSLeay-standalone.json"
import _LX_SSPL_1_0 from "./SSPL-1.0.json"
import _LX_SugarCRM_1_1_3 from "./SugarCRM-1.1.3.json"
import _LX_SUL_1_0 from "./SUL-1.0.json"
import _LX_Sun_PPP from "./Sun-PPP.json"
import _LX_Sun_PPP_2000 from "./Sun-PPP-2000.json"
import _LX_SunPro from "./SunPro.json"
import _LX_SWL from "./SWL.json"
import _LX_swrule from "./swrule.json"
import _LX_Symlinks from "./Symlinks.json"
import _LX_TAPR_OHL_1_0 from "./TAPR-OHL-1.0.json"
import _LX_TCL from "./TCL.json"
import _LX_TCP_wrappers from "./TCP-wrappers.json"
import _LX_TekHVC from "./TekHVC.json"
import _LX_TermReadKey from "./TermReadKey.json"
import _LX_TGPPL_1_0 from "./TGPPL-1.0.json"
import _LX_ThirdEye from "./ThirdEye.json"
import _LX_threeparttable from "./threeparttable.json"
import _LX_TMate from "./TMate.json"
import _LX_TORQUE_1_1 from "./TORQUE-1.1.json"
import _LX_TOSL from "./TOSL.json"
import _LX_TPDL from "./TPDL.json"
import _LX_TPL_1_0 from "./TPL-1.0.json"
import _LX_TrustedQSL from "./TrustedQSL.json"
import _LX_TTWL from "./TTWL.json"
import _LX_TTYP0 from "./TTYP0.json"
import _LX_TU_Berlin_1_0 from "./TU-Berlin-1.0.json"
import _LX_TU_Berlin_2_0 from "./TU-Berlin-2.0.json"
import _LX_Ubuntu_font_1_0 from "./Ubuntu-font-1.0.json"
import _LX_UCAR from "./UCAR.json"
import _LX_UCL_1_0 from "./UCL-1.0.json"
import _LX_ulem from "./ulem.json"
import _LX_UMich_Merit from "./UMich-Merit.json"
import _LX_Unicode_3_0 from "./Unicode-3.0.json"
import _LX_Unicode_DFS_2015 from "./Unicode-DFS-2015.json"
import _LX_Unicode_DFS_2016 from "./Unicode-DFS-2016.json"
import _LX_Unicode_TOU from "./Unicode-TOU.json"
import _LX_UnixCrypt from "./UnixCrypt.json"
import _LX_Unlicense from "./Unlicense.json"
import _LX_Unlicense_libtelnet from "./Unlicense-libtelnet.json"
import _LX_Unlicense_libwhirlpool from "./Unlicense-libwhirlpool.json"
import _LX_UnRAR from "./UnRAR.json"
import _LX_UPL_1_0 from "./UPL-1.0.json"
import _LX_URT_RLE from "./URT-RLE.json"
import _LX_Vim from "./Vim.json"
import _LX_Vixie_Cron from "./Vixie-Cron.json"
import _LX_VOSTROM from "./VOSTROM.json"
import _LX_VSL_1_0 from "./VSL-1.0.json"
import _LX_W3C from "./W3C.json"
import _LX_W3C_19980720 from "./W3C-19980720.json"
import _LX_W3C_20150513 from "./W3C-20150513.json"
import _LX_w3m from "./w3m.json"
import _LX_Watcom_1_0 from "./Watcom-1.0.json"
import _LX_Widget_Workshop from "./Widget-Workshop.json"
import _LX_WordNet from "./WordNet.json"
import _LX_Wsuipa from "./Wsuipa.json"
import _LX_WTFNMFPL from "./WTFNMFPL.json"
import _LX_WTFPL from "./WTFPL.json"
import _LX_wwl from "./wwl.json"
import _LX_X11 from "./X11.json"
import _LX_X11_distribute_modifications_variant from "./X11-distribute-modifications-variant.json"
import _LX_X11_no_permit_persons from "./X11-no-permit-persons.json"
import _LX_X11_swapped from "./X11-swapped.json"
import _LX_Xdebug_1_03 from "./Xdebug-1.03.json"
import _LX_Xerox from "./Xerox.json"
import _LX_Xfig from "./Xfig.json"
import _LX_XFree86_1_1 from "./XFree86-1.1.json"
import _LX_xinetd from "./xinetd.json"
import _LX_xkeyboard_config_Zinoviev from "./xkeyboard-config-Zinoviev.json"
import _LX_xlock from "./xlock.json"
import _LX_Xnet from "./Xnet.json"
import _LX_xpp from "./xpp.json"
import _LX_XSkat from "./XSkat.json"
import _LX_xzoom from "./xzoom.json"
import _LX_YPL_1_0 from "./YPL-1.0.json"
import _LX_YPL_1_1 from "./YPL-1.1.json"
import _LX_Zed from "./Zed.json"
import _LX_Zeeff from "./Zeeff.json"
import _LX_Zend_2_0 from "./Zend-2.0.json"
import _LX_Zimbra_1_3 from "./Zimbra-1.3.json"
import _LX_Zimbra_1_4 from "./Zimbra-1.4.json"
import _LX_Zlib from "./Zlib.json"
import _LX_zlib_acknowledgement from "./zlib-acknowledgement.json"
import _LX_ZPL_1_1 from "./ZPL-1.1.json"
import _LX_ZPL_2_0 from "./ZPL-2.0.json"
import _LX_ZPL_2_1 from "./ZPL-2.1.json"

export interface LicenseData {
    id: string
    name: string
    text: string
}

export const licenses: Record<string, LicenseData | undefined> = {
    "0BSD": _LX_0BSD,
    "3D-Slicer-1.0": _LX_3D_Slicer_1_0,
    "AAL": _LX_AAL,
    "Abstyles": _LX_Abstyles,
    "AdaCore-doc": _LX_AdaCore_doc,
    "Adobe-2006": _LX_Adobe_2006,
    "Adobe-Display-PostScript": _LX_Adobe_Display_PostScript,
    "Adobe-Glyph": _LX_Adobe_Glyph,
    "Adobe-Utopia": _LX_Adobe_Utopia,
    "ADSL": _LX_ADSL,
    "Advanced-Cryptics-Dictionary": _LX_Advanced_Cryptics_Dictionary,
    "AFL-1.1": _LX_AFL_1_1,
    "AFL-1.2": _LX_AFL_1_2,
    "AFL-2.0": _LX_AFL_2_0,
    "AFL-2.1": _LX_AFL_2_1,
    "AFL-3.0": _LX_AFL_3_0,
    "Afmparse": _LX_Afmparse,
    "AGPL-1.0-only": _LX_AGPL_1_0_only,
    "AGPL-1.0-or-later": _LX_AGPL_1_0_or_later,
    "AGPL-3.0-only": _LX_AGPL_3_0_only,
    "AGPL-3.0-or-later": _LX_AGPL_3_0_or_later,
    "Aladdin": _LX_Aladdin,
    "ALGLIB-Documentation": _LX_ALGLIB_Documentation,
    "AMD-newlib": _LX_AMD_newlib,
    "AMDPLPA": _LX_AMDPLPA,
    "AML": _LX_AML,
    "AML-glslang": _LX_AML_glslang,
    "AMPAS": _LX_AMPAS,
    "ANTLR-PD": _LX_ANTLR_PD,
    "ANTLR-PD-fallback": _LX_ANTLR_PD_fallback,
    "any-OSI": _LX_any_OSI,
    "any-OSI-perl-modules": _LX_any_OSI_perl_modules,
    "Apache-1.0": _LX_Apache_1_0,
    "Apache-1.1": _LX_Apache_1_1,
    "Apache-2.0": _LX_Apache_2_0,
    "APAFML": _LX_APAFML,
    "APL-1.0": _LX_APL_1_0,
    "App-s2p": _LX_App_s2p,
    "APSL-1.0": _LX_APSL_1_0,
    "APSL-1.1": _LX_APSL_1_1,
    "APSL-1.2": _LX_APSL_1_2,
    "APSL-2.0": _LX_APSL_2_0,
    "Arphic-1999": _LX_Arphic_1999,
    "Artistic-1.0": _LX_Artistic_1_0,
    "Artistic-1.0-cl8": _LX_Artistic_1_0_cl8,
    "Artistic-1.0-Perl": _LX_Artistic_1_0_Perl,
    "Artistic-2.0": _LX_Artistic_2_0,
    "Artistic-dist": _LX_Artistic_dist,
    "Aspell-RU": _LX_Aspell_RU,
    "ASWF-Digital-Assets-1.0": _LX_ASWF_Digital_Assets_1_0,
    "ASWF-Digital-Assets-1.1": _LX_ASWF_Digital_Assets_1_1,
    "Baekmuk": _LX_Baekmuk,
    "Bahyph": _LX_Bahyph,
    "Barr": _LX_Barr,
    "bcrypt-Solar-Designer": _LX_bcrypt_Solar_Designer,
    "Beerware": _LX_Beerware,
    "Bitstream-Charter": _LX_Bitstream_Charter,
    "Bitstream-Vera": _LX_Bitstream_Vera,
    "BitTorrent-1.0": _LX_BitTorrent_1_0,
    "BitTorrent-1.1": _LX_BitTorrent_1_1,
    "blessing": _LX_blessing,
    "BlueOak-1.0.0": _LX_BlueOak_1_0_0,
    "Boehm-GC": _LX_Boehm_GC,
    "Boehm-GC-without-fee": _LX_Boehm_GC_without_fee,
    "BOLA-1.1": _LX_BOLA_1_1,
    "Borceux": _LX_Borceux,
    "Brian-Gladman-2-Clause": _LX_Brian_Gladman_2_Clause,
    "Brian-Gladman-3-Clause": _LX_Brian_Gladman_3_Clause,
    "Brian-Gladman-3-Clause-no-conversion": _LX_Brian_Gladman_3_Clause_no_conversion,
    "BSD-1-Clause": _LX_BSD_1_Clause,
    "BSD-2-Clause": _LX_BSD_2_Clause,
    "BSD-2-Clause-Darwin": _LX_BSD_2_Clause_Darwin,
    "BSD-2-Clause-first-lines": _LX_BSD_2_Clause_first_lines,
    "BSD-2-Clause-Patent": _LX_BSD_2_Clause_Patent,
    "BSD-2-Clause-pkgconf-disclaimer": _LX_BSD_2_Clause_pkgconf_disclaimer,
    "BSD-2-Clause-Views": _LX_BSD_2_Clause_Views,
    "BSD-3-Clause": _LX_BSD_3_Clause,
    "BSD-3-Clause-acpica": _LX_BSD_3_Clause_acpica,
    "BSD-3-Clause-Attribution": _LX_BSD_3_Clause_Attribution,
    "BSD-3-Clause-Clear": _LX_BSD_3_Clause_Clear,
    "BSD-3-Clause-flex": _LX_BSD_3_Clause_flex,
    "BSD-3-Clause-HP": _LX_BSD_3_Clause_HP,
    "BSD-3-Clause-LBNL": _LX_BSD_3_Clause_LBNL,
    "BSD-3-Clause-Modification": _LX_BSD_3_Clause_Modification,
    "BSD-3-Clause-No-Military-License": _LX_BSD_3_Clause_No_Military_License,
    "BSD-3-Clause-No-Nuclear-License": _LX_BSD_3_Clause_No_Nuclear_License,
    "BSD-3-Clause-No-Nuclear-License-2014": _LX_BSD_3_Clause_No_Nuclear_License_2014,
    "BSD-3-Clause-No-Nuclear-Warranty": _LX_BSD_3_Clause_No_Nuclear_Warranty,
    "BSD-3-Clause-Open-MPI": _LX_BSD_3_Clause_Open_MPI,
    "BSD-3-Clause-Sun": _LX_BSD_3_Clause_Sun,
    "BSD-3-Clause-Tso": _LX_BSD_3_Clause_Tso,
    "BSD-4-Clause": _LX_BSD_4_Clause,
    "BSD-4-Clause-Shortened": _LX_BSD_4_Clause_Shortened,
    "BSD-4-Clause-UC": _LX_BSD_4_Clause_UC,
    "BSD-4.3RENO": _LX_BSD_4_3RENO,
    "BSD-4.3TAHOE": _LX_BSD_4_3TAHOE,
    "BSD-Advertising-Acknowledgement": _LX_BSD_Advertising_Acknowledgement,
    "BSD-Attribution-HPND-disclaimer": _LX_BSD_Attribution_HPND_disclaimer,
    "BSD-Inferno-Nettverk": _LX_BSD_Inferno_Nettverk,
    "BSD-Mark-Modifications": _LX_BSD_Mark_Modifications,
    "BSD-Protection": _LX_BSD_Protection,
    "BSD-Source-beginning-file": _LX_BSD_Source_beginning_file,
    "BSD-Source-Code": _LX_BSD_Source_Code,
    "BSD-Systemics": _LX_BSD_Systemics,
    "BSD-Systemics-W3Works": _LX_BSD_Systemics_W3Works,
    "BSL-1.0": _LX_BSL_1_0,
    "Buddy": _LX_Buddy,
    "BUSL-1.1": _LX_BUSL_1_1,
    "bzip2-1.0.6": _LX_bzip2_1_0_6,
    "C-UDA-1.0": _LX_C_UDA_1_0,
    "CAL-1.0": _LX_CAL_1_0,
    "CAL-1.0-Combined-Work-Exception": _LX_CAL_1_0_Combined_Work_Exception,
    "Caldera": _LX_Caldera,
    "Caldera-no-preamble": _LX_Caldera_no_preamble,
    "CAPEC-tou": _LX_CAPEC_tou,
    "Catharon": _LX_Catharon,
    "CATOSL-1.1": _LX_CATOSL_1_1,
    "CC-BY-1.0": _LX_CC_BY_1_0,
    "CC-BY-2.0": _LX_CC_BY_2_0,
    "CC-BY-2.5": _LX_CC_BY_2_5,
    "CC-BY-2.5-AU": _LX_CC_BY_2_5_AU,
    "CC-BY-3.0": _LX_CC_BY_3_0,
    "CC-BY-3.0-AT": _LX_CC_BY_3_0_AT,
    "CC-BY-3.0-AU": _LX_CC_BY_3_0_AU,
    "CC-BY-3.0-DE": _LX_CC_BY_3_0_DE,
    "CC-BY-3.0-IGO": _LX_CC_BY_3_0_IGO,
    "CC-BY-3.0-NL": _LX_CC_BY_3_0_NL,
    "CC-BY-3.0-US": _LX_CC_BY_3_0_US,
    "CC-BY-4.0": _LX_CC_BY_4_0,
    "CC-BY-NC-1.0": _LX_CC_BY_NC_1_0,
    "CC-BY-NC-2.0": _LX_CC_BY_NC_2_0,
    "CC-BY-NC-2.5": _LX_CC_BY_NC_2_5,
    "CC-BY-NC-3.0": _LX_CC_BY_NC_3_0,
    "CC-BY-NC-3.0-DE": _LX_CC_BY_NC_3_0_DE,
    "CC-BY-NC-4.0": _LX_CC_BY_NC_4_0,
    "CC-BY-NC-ND-1.0": _LX_CC_BY_NC_ND_1_0,
    "CC-BY-NC-ND-2.0": _LX_CC_BY_NC_ND_2_0,
    "CC-BY-NC-ND-2.5": _LX_CC_BY_NC_ND_2_5,
    "CC-BY-NC-ND-3.0": _LX_CC_BY_NC_ND_3_0,
    "CC-BY-NC-ND-3.0-DE": _LX_CC_BY_NC_ND_3_0_DE,
    "CC-BY-NC-ND-3.0-IGO": _LX_CC_BY_NC_ND_3_0_IGO,
    "CC-BY-NC-ND-4.0": _LX_CC_BY_NC_ND_4_0,
    "CC-BY-NC-SA-1.0": _LX_CC_BY_NC_SA_1_0,
    "CC-BY-NC-SA-2.0": _LX_CC_BY_NC_SA_2_0,
    "CC-BY-NC-SA-2.0-DE": _LX_CC_BY_NC_SA_2_0_DE,
    "CC-BY-NC-SA-2.0-FR": _LX_CC_BY_NC_SA_2_0_FR,
    "CC-BY-NC-SA-2.0-UK": _LX_CC_BY_NC_SA_2_0_UK,
    "CC-BY-NC-SA-2.5": _LX_CC_BY_NC_SA_2_5,
    "CC-BY-NC-SA-3.0": _LX_CC_BY_NC_SA_3_0,
    "CC-BY-NC-SA-3.0-DE": _LX_CC_BY_NC_SA_3_0_DE,
    "CC-BY-NC-SA-3.0-IGO": _LX_CC_BY_NC_SA_3_0_IGO,
    "CC-BY-NC-SA-4.0": _LX_CC_BY_NC_SA_4_0,
    "CC-BY-ND-1.0": _LX_CC_BY_ND_1_0,
    "CC-BY-ND-2.0": _LX_CC_BY_ND_2_0,
    "CC-BY-ND-2.5": _LX_CC_BY_ND_2_5,
    "CC-BY-ND-3.0": _LX_CC_BY_ND_3_0,
    "CC-BY-ND-3.0-DE": _LX_CC_BY_ND_3_0_DE,
    "CC-BY-ND-4.0": _LX_CC_BY_ND_4_0,
    "CC-BY-SA-1.0": _LX_CC_BY_SA_1_0,
    "CC-BY-SA-2.0": _LX_CC_BY_SA_2_0,
    "CC-BY-SA-2.0-UK": _LX_CC_BY_SA_2_0_UK,
    "CC-BY-SA-2.1-JP": _LX_CC_BY_SA_2_1_JP,
    "CC-BY-SA-2.5": _LX_CC_BY_SA_2_5,
    "CC-BY-SA-3.0": _LX_CC_BY_SA_3_0,
    "CC-BY-SA-3.0-AT": _LX_CC_BY_SA_3_0_AT,
    "CC-BY-SA-3.0-DE": _LX_CC_BY_SA_3_0_DE,
    "CC-BY-SA-3.0-IGO": _LX_CC_BY_SA_3_0_IGO,
    "CC-BY-SA-4.0": _LX_CC_BY_SA_4_0,
    "CC-PDDC": _LX_CC_PDDC,
    "CC-PDM-1.0": _LX_CC_PDM_1_0,
    "CC-SA-1.0": _LX_CC_SA_1_0,
    "CC0-1.0": _LX_CC0_1_0,
    "CDDL-1.0": _LX_CDDL_1_0,
    "CDDL-1.1": _LX_CDDL_1_1,
    "CDL-1.0": _LX_CDL_1_0,
    "CDLA-Permissive-1.0": _LX_CDLA_Permissive_1_0,
    "CDLA-Permissive-2.0": _LX_CDLA_Permissive_2_0,
    "CDLA-Sharing-1.0": _LX_CDLA_Sharing_1_0,
    "CECILL-1.0": _LX_CECILL_1_0,
    "CECILL-1.1": _LX_CECILL_1_1,
    "CECILL-2.0": _LX_CECILL_2_0,
    "CECILL-2.1": _LX_CECILL_2_1,
    "CECILL-B": _LX_CECILL_B,
    "CECILL-C": _LX_CECILL_C,
    "CERN-OHL-1.1": _LX_CERN_OHL_1_1,
    "CERN-OHL-1.2": _LX_CERN_OHL_1_2,
    "CERN-OHL-P-2.0": _LX_CERN_OHL_P_2_0,
    "CERN-OHL-S-2.0": _LX_CERN_OHL_S_2_0,
    "CERN-OHL-W-2.0": _LX_CERN_OHL_W_2_0,
    "CFITSIO": _LX_CFITSIO,
    "check-cvs": _LX_check_cvs,
    "checkmk": _LX_checkmk,
    "ClArtistic": _LX_ClArtistic,
    "Clips": _LX_Clips,
    "CMU-Mach": _LX_CMU_Mach,
    "CMU-Mach-nodoc": _LX_CMU_Mach_nodoc,
    "CNRI-Jython": _LX_CNRI_Jython,
    "CNRI-Python": _LX_CNRI_Python,
    "CNRI-Python-GPL-Compatible": _LX_CNRI_Python_GPL_Compatible,
    "COIL-1.0": _LX_COIL_1_0,
    "Community-Spec-1.0": _LX_Community_Spec_1_0,
    "Condor-1.1": _LX_Condor_1_1,
    "copyleft-next-0.3.0": _LX_copyleft_next_0_3_0,
    "copyleft-next-0.3.1": _LX_copyleft_next_0_3_1,
    "Cornell-Lossless-JPEG": _LX_Cornell_Lossless_JPEG,
    "CPAL-1.0": _LX_CPAL_1_0,
    "CPL-1.0": _LX_CPL_1_0,
    "CPOL-1.02": _LX_CPOL_1_02,
    "Cronyx": _LX_Cronyx,
    "Crossword": _LX_Crossword,
    "CryptoSwift": _LX_CryptoSwift,
    "CrystalStacker": _LX_CrystalStacker,
    "CUA-OPL-1.0": _LX_CUA_OPL_1_0,
    "Cube": _LX_Cube,
    "curl": _LX_curl,
    "cve-tou": _LX_cve_tou,
    "D-FSL-1.0": _LX_D_FSL_1_0,
    "DEC-3-Clause": _LX_DEC_3_Clause,
    "diffmark": _LX_diffmark,
    "DL-DE-BY-2.0": _LX_DL_DE_BY_2_0,
    "DL-DE-ZERO-2.0": _LX_DL_DE_ZERO_2_0,
    "DOC": _LX_DOC,
    "DocBook-DTD": _LX_DocBook_DTD,
    "DocBook-Schema": _LX_DocBook_Schema,
    "DocBook-Stylesheet": _LX_DocBook_Stylesheet,
    "DocBook-XML": _LX_DocBook_XML,
    "Dotseqn": _LX_Dotseqn,
    "DRL-1.0": _LX_DRL_1_0,
    "DRL-1.1": _LX_DRL_1_1,
    "DSDP": _LX_DSDP,
    "dtoa": _LX_dtoa,
    "dvipdfm": _LX_dvipdfm,
    "ECL-1.0": _LX_ECL_1_0,
    "ECL-2.0": _LX_ECL_2_0,
    "EFL-1.0": _LX_EFL_1_0,
    "EFL-2.0": _LX_EFL_2_0,
    "eGenix": _LX_eGenix,
    "Elastic-2.0": _LX_Elastic_2_0,
    "Entessa": _LX_Entessa,
    "EPICS": _LX_EPICS,
    "EPL-1.0": _LX_EPL_1_0,
    "EPL-2.0": _LX_EPL_2_0,
    "ErlPL-1.1": _LX_ErlPL_1_1,
    "ESA-PL-permissive-2.4": _LX_ESA_PL_permissive_2_4,
    "ESA-PL-strong-copyleft-2.4": _LX_ESA_PL_strong_copyleft_2_4,
    "ESA-PL-weak-copyleft-2.4": _LX_ESA_PL_weak_copyleft_2_4,
    "etalab-2.0": _LX_etalab_2_0,
    "EUDatagrid": _LX_EUDatagrid,
    "EUPL-1.0": _LX_EUPL_1_0,
    "EUPL-1.1": _LX_EUPL_1_1,
    "EUPL-1.2": _LX_EUPL_1_2,
    "Eurosym": _LX_Eurosym,
    "Fair": _LX_Fair,
    "FBM": _LX_FBM,
    "FDK-AAC": _LX_FDK_AAC,
    "Ferguson-Twofish": _LX_Ferguson_Twofish,
    "Frameworx-1.0": _LX_Frameworx_1_0,
    "FreeBSD-DOC": _LX_FreeBSD_DOC,
    "FreeImage": _LX_FreeImage,
    "FSFAP": _LX_FSFAP,
    "FSFAP-no-warranty-disclaimer": _LX_FSFAP_no_warranty_disclaimer,
    "FSFUL": _LX_FSFUL,
    "FSFULLR": _LX_FSFULLR,
    "FSFULLRSD": _LX_FSFULLRSD,
    "FSFULLRWD": _LX_FSFULLRWD,
    "FSL-1.1-ALv2": _LX_FSL_1_1_ALv2,
    "FSL-1.1-MIT": _LX_FSL_1_1_MIT,
    "FTL": _LX_FTL,
    "Furuseth": _LX_Furuseth,
    "fwlw": _LX_fwlw,
    "Game-Programming-Gems": _LX_Game_Programming_Gems,
    "GCR-docs": _LX_GCR_docs,
    "GD": _LX_GD,
    "generic-xts": _LX_generic_xts,
    "GFDL-1.1-invariants-only": _LX_GFDL_1_1_invariants_only,
    "GFDL-1.1-invariants-or-later": _LX_GFDL_1_1_invariants_or_later,
    "GFDL-1.1-no-invariants-only": _LX_GFDL_1_1_no_invariants_only,
    "GFDL-1.1-no-invariants-or-later": _LX_GFDL_1_1_no_invariants_or_later,
    "GFDL-1.1-only": _LX_GFDL_1_1_only,
    "GFDL-1.1-or-later": _LX_GFDL_1_1_or_later,
    "GFDL-1.2-invariants-only": _LX_GFDL_1_2_invariants_only,
    "GFDL-1.2-invariants-or-later": _LX_GFDL_1_2_invariants_or_later,
    "GFDL-1.2-no-invariants-only": _LX_GFDL_1_2_no_invariants_only,
    "GFDL-1.2-no-invariants-or-later": _LX_GFDL_1_2_no_invariants_or_later,
    "GFDL-1.2-only": _LX_GFDL_1_2_only,
    "GFDL-1.2-or-later": _LX_GFDL_1_2_or_later,
    "GFDL-1.3-invariants-only": _LX_GFDL_1_3_invariants_only,
    "GFDL-1.3-invariants-or-later": _LX_GFDL_1_3_invariants_or_later,
    "GFDL-1.3-no-invariants-only": _LX_GFDL_1_3_no_invariants_only,
    "GFDL-1.3-no-invariants-or-later": _LX_GFDL_1_3_no_invariants_or_later,
    "GFDL-1.3-only": _LX_GFDL_1_3_only,
    "GFDL-1.3-or-later": _LX_GFDL_1_3_or_later,
    "Giftware": _LX_Giftware,
    "GL2PS": _LX_GL2PS,
    "Glide": _LX_Glide,
    "Glulxe": _LX_Glulxe,
    "GLWTPL": _LX_GLWTPL,
    "gnuplot": _LX_gnuplot,
    "GPL-1.0-only": _LX_GPL_1_0_only,
    "GPL-1.0-or-later": _LX_GPL_1_0_or_later,
    "GPL-2.0-only": _LX_GPL_2_0_only,
    "GPL-2.0-or-later": _LX_GPL_2_0_or_later,
    "GPL-3.0-only": _LX_GPL_3_0_only,
    "GPL-3.0-or-later": _LX_GPL_3_0_or_later,
    "Graphics-Gems": _LX_Graphics_Gems,
    "gSOAP-1.3b": _LX_gSOAP_1_3b,
    "gtkbook": _LX_gtkbook,
    "Gutmann": _LX_Gutmann,
    "HaskellReport": _LX_HaskellReport,
    "HDF5": _LX_HDF5,
    "hdparm": _LX_hdparm,
    "HIDAPI": _LX_HIDAPI,
    "Hippocratic-2.1": _LX_Hippocratic_2_1,
    "HP-1986": _LX_HP_1986,
    "HP-1989": _LX_HP_1989,
    "HPND": _LX_HPND,
    "HPND-DEC": _LX_HPND_DEC,
    "HPND-doc": _LX_HPND_doc,
    "HPND-doc-sell": _LX_HPND_doc_sell,
    "HPND-export-US": _LX_HPND_export_US,
    "HPND-export-US-acknowledgement": _LX_HPND_export_US_acknowledgement,
    "HPND-export-US-modify": _LX_HPND_export_US_modify,
    "HPND-export2-US": _LX_HPND_export2_US,
    "HPND-Fenneberg-Livingston": _LX_HPND_Fenneberg_Livingston,
    "HPND-INRIA-IMAG": _LX_HPND_INRIA_IMAG,
    "HPND-Intel": _LX_HPND_Intel,
    "HPND-Kevlin-Henney": _LX_HPND_Kevlin_Henney,
    "HPND-Markus-Kuhn": _LX_HPND_Markus_Kuhn,
    "HPND-merchantability-variant": _LX_HPND_merchantability_variant,
    "HPND-MIT-disclaimer": _LX_HPND_MIT_disclaimer,
    "HPND-Netrek": _LX_HPND_Netrek,
    "HPND-Pbmplus": _LX_HPND_Pbmplus,
    "HPND-sell-MIT-disclaimer-xserver": _LX_HPND_sell_MIT_disclaimer_xserver,
    "HPND-sell-regexpr": _LX_HPND_sell_regexpr,
    "HPND-sell-variant": _LX_HPND_sell_variant,
    "HPND-sell-variant-critical-systems": _LX_HPND_sell_variant_critical_systems,
    "HPND-sell-variant-MIT-disclaimer": _LX_HPND_sell_variant_MIT_disclaimer,
    "HPND-sell-variant-MIT-disclaimer-rev": _LX_HPND_sell_variant_MIT_disclaimer_rev,
    "HPND-SMC": _LX_HPND_SMC,
    "HPND-UC": _LX_HPND_UC,
    "HPND-UC-export-US": _LX_HPND_UC_export_US,
    "HTMLTIDY": _LX_HTMLTIDY,
    "hyphen-bulgarian": _LX_hyphen_bulgarian,
    "IBM-pibs": _LX_IBM_pibs,
    "ICU": _LX_ICU,
    "IEC-Code-Components-EULA": _LX_IEC_Code_Components_EULA,
    "IJG": _LX_IJG,
    "IJG-short": _LX_IJG_short,
    "ImageMagick": _LX_ImageMagick,
    "iMatix": _LX_iMatix,
    "Imlib2": _LX_Imlib2,
    "Info-ZIP": _LX_Info_ZIP,
    "Inner-Net-2.0": _LX_Inner_Net_2_0,
    "InnoSetup": _LX_InnoSetup,
    "Intel": _LX_Intel,
    "Intel-ACPI": _LX_Intel_ACPI,
    "Interbase-1.0": _LX_Interbase_1_0,
    "IPA": _LX_IPA,
    "IPL-1.0": _LX_IPL_1_0,
    "ISC": _LX_ISC,
    "ISC-Veillard": _LX_ISC_Veillard,
    "ISO-permission": _LX_ISO_permission,
    "Jam": _LX_Jam,
    "JasPer-2.0": _LX_JasPer_2_0,
    "jove": _LX_jove,
    "JPL-image": _LX_JPL_image,
    "JPNIC": _LX_JPNIC,
    "JSON": _LX_JSON,
    "Kastrup": _LX_Kastrup,
    "Kazlib": _LX_Kazlib,
    "Knuth-CTAN": _LX_Knuth_CTAN,
    "LAL-1.2": _LX_LAL_1_2,
    "LAL-1.3": _LX_LAL_1_3,
    "Latex2e": _LX_Latex2e,
    "Latex2e-translated-notice": _LX_Latex2e_translated_notice,
    "Leptonica": _LX_Leptonica,
    "LGPL-2.0-only": _LX_LGPL_2_0_only,
    "LGPL-2.0-or-later": _LX_LGPL_2_0_or_later,
    "LGPL-2.1-only": _LX_LGPL_2_1_only,
    "LGPL-2.1-or-later": _LX_LGPL_2_1_or_later,
    "LGPL-3.0-only": _LX_LGPL_3_0_only,
    "LGPL-3.0-or-later": _LX_LGPL_3_0_or_later,
    "LGPLLR": _LX_LGPLLR,
    "Libpng": _LX_Libpng,
    "libpng-1.6.35": _LX_libpng_1_6_35,
    "libpng-2.0": _LX_libpng_2_0,
    "libselinux-1.0": _LX_libselinux_1_0,
    "libtiff": _LX_libtiff,
    "libutil-David-Nugent": _LX_libutil_David_Nugent,
    "LiLiQ-P-1.1": _LX_LiLiQ_P_1_1,
    "LiLiQ-R-1.1": _LX_LiLiQ_R_1_1,
    "LiLiQ-Rplus-1.1": _LX_LiLiQ_Rplus_1_1,
    "Linux-man-pages-1-para": _LX_Linux_man_pages_1_para,
    "Linux-man-pages-copyleft": _LX_Linux_man_pages_copyleft,
    "Linux-man-pages-copyleft-2-para": _LX_Linux_man_pages_copyleft_2_para,
    "Linux-man-pages-copyleft-var": _LX_Linux_man_pages_copyleft_var,
    "Linux-OpenIB": _LX_Linux_OpenIB,
    "LOOP": _LX_LOOP,
    "LPD-document": _LX_LPD_document,
    "LPL-1.0": _LX_LPL_1_0,
    "LPL-1.02": _LX_LPL_1_02,
    "LPPL-1.0": _LX_LPPL_1_0,
    "LPPL-1.1": _LX_LPPL_1_1,
    "LPPL-1.2": _LX_LPPL_1_2,
    "LPPL-1.3a": _LX_LPPL_1_3a,
    "LPPL-1.3c": _LX_LPPL_1_3c,
    "lsof": _LX_lsof,
    "Lucida-Bitmap-Fonts": _LX_Lucida_Bitmap_Fonts,
    "LZMA-SDK-9.11-to-9.20": _LX_LZMA_SDK_9_11_to_9_20,
    "LZMA-SDK-9.22": _LX_LZMA_SDK_9_22,
    "Mackerras-3-Clause": _LX_Mackerras_3_Clause,
    "Mackerras-3-Clause-acknowledgment": _LX_Mackerras_3_Clause_acknowledgment,
    "magaz": _LX_magaz,
    "mailprio": _LX_mailprio,
    "MakeIndex": _LX_MakeIndex,
    "man2html": _LX_man2html,
    "Martin-Birgmeier": _LX_Martin_Birgmeier,
    "McPhee-slideshow": _LX_McPhee_slideshow,
    "metamail": _LX_metamail,
    "Minpack": _LX_Minpack,
    "MIPS": _LX_MIPS,
    "MirOS": _LX_MirOS,
    "MIT": _LX_MIT,
    "MIT-0": _LX_MIT_0,
    "MIT-advertising": _LX_MIT_advertising,
    "MIT-Click": _LX_MIT_Click,
    "MIT-CMU": _LX_MIT_CMU,
    "MIT-enna": _LX_MIT_enna,
    "MIT-feh": _LX_MIT_feh,
    "MIT-Festival": _LX_MIT_Festival,
    "MIT-Khronos-old": _LX_MIT_Khronos_old,
    "MIT-Modern-Variant": _LX_MIT_Modern_Variant,
    "MIT-open-group": _LX_MIT_open_group,
    "MIT-STK": _LX_MIT_STK,
    "MIT-testregex": _LX_MIT_testregex,
    "MIT-Wu": _LX_MIT_Wu,
    "MITNFA": _LX_MITNFA,
    "MMIXware": _LX_MMIXware,
    "MMPL-1.0.1": _LX_MMPL_1_0_1,
    "Motosoto": _LX_Motosoto,
    "MPEG-SSG": _LX_MPEG_SSG,
    "mpi-permissive": _LX_mpi_permissive,
    "mpich2": _LX_mpich2,
    "MPL-1.0": _LX_MPL_1_0,
    "MPL-1.1": _LX_MPL_1_1,
    "MPL-2.0": _LX_MPL_2_0,
    "MPL-2.0-no-copyleft-exception": _LX_MPL_2_0_no_copyleft_exception,
    "mplus": _LX_mplus,
    "MS-LPL": _LX_MS_LPL,
    "MS-PL": _LX_MS_PL,
    "MS-RL": _LX_MS_RL,
    "MTLL": _LX_MTLL,
    "MulanPSL-1.0": _LX_MulanPSL_1_0,
    "MulanPSL-2.0": _LX_MulanPSL_2_0,
    "Multics": _LX_Multics,
    "Mup": _LX_Mup,
    "MVT-1.1": _LX_MVT_1_1,
    "NAIST-2003": _LX_NAIST_2003,
    "NASA-1.3": _LX_NASA_1_3,
    "Naumen": _LX_Naumen,
    "NBPL-1.0": _LX_NBPL_1_0,
    "NCBI-PD": _LX_NCBI_PD,
    "NCGL-UK-2.0": _LX_NCGL_UK_2_0,
    "NCL": _LX_NCL,
    "NCSA": _LX_NCSA,
    "NetCDF": _LX_NetCDF,
    "Newsletr": _LX_Newsletr,
    "NGPL": _LX_NGPL,
    "ngrep": _LX_ngrep,
    "NICTA-1.0": _LX_NICTA_1_0,
    "NIST-PD": _LX_NIST_PD,
    "NIST-PD-fallback": _LX_NIST_PD_fallback,
    "NIST-PD-TNT": _LX_NIST_PD_TNT,
    "NIST-Software": _LX_NIST_Software,
    "NLOD-1.0": _LX_NLOD_1_0,
    "NLOD-2.0": _LX_NLOD_2_0,
    "NLPL": _LX_NLPL,
    "Nokia": _LX_Nokia,
    "NOSL": _LX_NOSL,
    "Noweb": _LX_Noweb,
    "NPL-1.0": _LX_NPL_1_0,
    "NPL-1.1": _LX_NPL_1_1,
    "NPOSL-3.0": _LX_NPOSL_3_0,
    "NRL": _LX_NRL,
    "NTIA-PD": _LX_NTIA_PD,
    "NTP": _LX_NTP,
    "NTP-0": _LX_NTP_0,
    "O-UDA-1.0": _LX_O_UDA_1_0,
    "OAR": _LX_OAR,
    "OCCT-PL": _LX_OCCT_PL,
    "OCLC-2.0": _LX_OCLC_2_0,
    "ODbL-1.0": _LX_ODbL_1_0,
    "ODC-By-1.0": _LX_ODC_By_1_0,
    "OFFIS": _LX_OFFIS,
    "OFL-1.0": _LX_OFL_1_0,
    "OFL-1.0-no-RFN": _LX_OFL_1_0_no_RFN,
    "OFL-1.0-RFN": _LX_OFL_1_0_RFN,
    "OFL-1.1": _LX_OFL_1_1,
    "OFL-1.1-no-RFN": _LX_OFL_1_1_no_RFN,
    "OFL-1.1-RFN": _LX_OFL_1_1_RFN,
    "OGC-1.0": _LX_OGC_1_0,
    "OGDL-Taiwan-1.0": _LX_OGDL_Taiwan_1_0,
    "OGL-Canada-2.0": _LX_OGL_Canada_2_0,
    "OGL-UK-1.0": _LX_OGL_UK_1_0,
    "OGL-UK-2.0": _LX_OGL_UK_2_0,
    "OGL-UK-3.0": _LX_OGL_UK_3_0,
    "OGTSL": _LX_OGTSL,
    "OLDAP-1.1": _LX_OLDAP_1_1,
    "OLDAP-1.2": _LX_OLDAP_1_2,
    "OLDAP-1.3": _LX_OLDAP_1_3,
    "OLDAP-1.4": _LX_OLDAP_1_4,
    "OLDAP-2.0": _LX_OLDAP_2_0,
    "OLDAP-2.0.1": _LX_OLDAP_2_0_1,
    "OLDAP-2.1": _LX_OLDAP_2_1,
    "OLDAP-2.2": _LX_OLDAP_2_2,
    "OLDAP-2.2.1": _LX_OLDAP_2_2_1,
    "OLDAP-2.2.2": _LX_OLDAP_2_2_2,
    "OLDAP-2.3": _LX_OLDAP_2_3,
    "OLDAP-2.4": _LX_OLDAP_2_4,
    "OLDAP-2.5": _LX_OLDAP_2_5,
    "OLDAP-2.6": _LX_OLDAP_2_6,
    "OLDAP-2.7": _LX_OLDAP_2_7,
    "OLDAP-2.8": _LX_OLDAP_2_8,
    "OLFL-1.3": _LX_OLFL_1_3,
    "OML": _LX_OML,
    "OpenMDW-1.0": _LX_OpenMDW_1_0,
    "OpenPBS-2.3": _LX_OpenPBS_2_3,
    "OpenSSL": _LX_OpenSSL,
    "OpenSSL-standalone": _LX_OpenSSL_standalone,
    "OpenVision": _LX_OpenVision,
    "OPL-1.0": _LX_OPL_1_0,
    "OPL-UK-3.0": _LX_OPL_UK_3_0,
    "OPUBL-1.0": _LX_OPUBL_1_0,
    "OSC-1.0": _LX_OSC_1_0,
    "OSET-PL-2.1": _LX_OSET_PL_2_1,
    "OSL-1.0": _LX_OSL_1_0,
    "OSL-1.1": _LX_OSL_1_1,
    "OSL-2.0": _LX_OSL_2_0,
    "OSL-2.1": _LX_OSL_2_1,
    "OSL-3.0": _LX_OSL_3_0,
    "OSSP": _LX_OSSP,
    "PADL": _LX_PADL,
    "ParaType-Free-Font-1.3": _LX_ParaType_Free_Font_1_3,
    "Parity-6.0.0": _LX_Parity_6_0_0,
    "Parity-7.0.0": _LX_Parity_7_0_0,
    "PDDL-1.0": _LX_PDDL_1_0,
    "PHP-3.0": _LX_PHP_3_0,
    "PHP-3.01": _LX_PHP_3_01,
    "Pixar": _LX_Pixar,
    "pkgconf": _LX_pkgconf,
    "Plexus": _LX_Plexus,
    "pnmstitch": _LX_pnmstitch,
    "PolyForm-Noncommercial-1.0.0": _LX_PolyForm_Noncommercial_1_0_0,
    "PolyForm-Small-Business-1.0.0": _LX_PolyForm_Small_Business_1_0_0,
    "PostgreSQL": _LX_PostgreSQL,
    "PPL": _LX_PPL,
    "PSF-2.0": _LX_PSF_2_0,
    "psfrag": _LX_psfrag,
    "psutils": _LX_psutils,
    "Python-2.0": _LX_Python_2_0,
    "Python-2.0.1": _LX_Python_2_0_1,
    "python-ldap": _LX_python_ldap,
    "Qhull": _LX_Qhull,
    "QPL-1.0": _LX_QPL_1_0,
    "QPL-1.0-INRIA-2004": _LX_QPL_1_0_INRIA_2004,
    "radvd": _LX_radvd,
    "Rdisc": _LX_Rdisc,
    "RHeCos-1.1": _LX_RHeCos_1_1,
    "RPL-1.1": _LX_RPL_1_1,
    "RPL-1.5": _LX_RPL_1_5,
    "RPSL-1.0": _LX_RPSL_1_0,
    "RSA-MD": _LX_RSA_MD,
    "RSCPL": _LX_RSCPL,
    "Ruby": _LX_Ruby,
    "Ruby-pty": _LX_Ruby_pty,
    "SAX-PD": _LX_SAX_PD,
    "SAX-PD-2.0": _LX_SAX_PD_2_0,
    "Saxpath": _LX_Saxpath,
    "SCEA": _LX_SCEA,
    "SchemeReport": _LX_SchemeReport,
    "Sendmail": _LX_Sendmail,
    "Sendmail-8.23": _LX_Sendmail_8_23,
    "Sendmail-Open-Source-1.1": _LX_Sendmail_Open_Source_1_1,
    "SGI-B-1.0": _LX_SGI_B_1_0,
    "SGI-B-1.1": _LX_SGI_B_1_1,
    "SGI-B-2.0": _LX_SGI_B_2_0,
    "SGI-OpenGL": _LX_SGI_OpenGL,
    "SGMLUG-PM": _LX_SGMLUG_PM,
    "SGP4": _LX_SGP4,
    "SHL-0.5": _LX_SHL_0_5,
    "SHL-0.51": _LX_SHL_0_51,
    "SimPL-2.0": _LX_SimPL_2_0,
    "SISSL": _LX_SISSL,
    "SISSL-1.2": _LX_SISSL_1_2,
    "SL": _LX_SL,
    "Sleepycat": _LX_Sleepycat,
    "SMAIL-GPL": _LX_SMAIL_GPL,
    "SMLNJ": _LX_SMLNJ,
    "SMPPL": _LX_SMPPL,
    "SNIA": _LX_SNIA,
    "snprintf": _LX_snprintf,
    "SOFA": _LX_SOFA,
    "softSurfer": _LX_softSurfer,
    "Soundex": _LX_Soundex,
    "Spencer-86": _LX_Spencer_86,
    "Spencer-94": _LX_Spencer_94,
    "Spencer-99": _LX_Spencer_99,
    "SPL-1.0": _LX_SPL_1_0,
    "ssh-keyscan": _LX_ssh_keyscan,
    "SSH-OpenSSH": _LX_SSH_OpenSSH,
    "SSH-short": _LX_SSH_short,
    "SSLeay-standalone": _LX_SSLeay_standalone,
    "SSPL-1.0": _LX_SSPL_1_0,
    "SugarCRM-1.1.3": _LX_SugarCRM_1_1_3,
    "SUL-1.0": _LX_SUL_1_0,
    "Sun-PPP": _LX_Sun_PPP,
    "Sun-PPP-2000": _LX_Sun_PPP_2000,
    "SunPro": _LX_SunPro,
    "SWL": _LX_SWL,
    "swrule": _LX_swrule,
    "Symlinks": _LX_Symlinks,
    "TAPR-OHL-1.0": _LX_TAPR_OHL_1_0,
    "TCL": _LX_TCL,
    "TCP-wrappers": _LX_TCP_wrappers,
    "TekHVC": _LX_TekHVC,
    "TermReadKey": _LX_TermReadKey,
    "TGPPL-1.0": _LX_TGPPL_1_0,
    "ThirdEye": _LX_ThirdEye,
    "threeparttable": _LX_threeparttable,
    "TMate": _LX_TMate,
    "TORQUE-1.1": _LX_TORQUE_1_1,
    "TOSL": _LX_TOSL,
    "TPDL": _LX_TPDL,
    "TPL-1.0": _LX_TPL_1_0,
    "TrustedQSL": _LX_TrustedQSL,
    "TTWL": _LX_TTWL,
    "TTYP0": _LX_TTYP0,
    "TU-Berlin-1.0": _LX_TU_Berlin_1_0,
    "TU-Berlin-2.0": _LX_TU_Berlin_2_0,
    "Ubuntu-font-1.0": _LX_Ubuntu_font_1_0,
    "UCAR": _LX_UCAR,
    "UCL-1.0": _LX_UCL_1_0,
    "ulem": _LX_ulem,
    "UMich-Merit": _LX_UMich_Merit,
    "Unicode-3.0": _LX_Unicode_3_0,
    "Unicode-DFS-2015": _LX_Unicode_DFS_2015,
    "Unicode-DFS-2016": _LX_Unicode_DFS_2016,
    "Unicode-TOU": _LX_Unicode_TOU,
    "UnixCrypt": _LX_UnixCrypt,
    "Unlicense": _LX_Unlicense,
    "Unlicense-libtelnet": _LX_Unlicense_libtelnet,
    "Unlicense-libwhirlpool": _LX_Unlicense_libwhirlpool,
    "UnRAR": _LX_UnRAR,
    "UPL-1.0": _LX_UPL_1_0,
    "URT-RLE": _LX_URT_RLE,
    "Vim": _LX_Vim,
    "Vixie-Cron": _LX_Vixie_Cron,
    "VOSTROM": _LX_VOSTROM,
    "VSL-1.0": _LX_VSL_1_0,
    "W3C": _LX_W3C,
    "W3C-19980720": _LX_W3C_19980720,
    "W3C-20150513": _LX_W3C_20150513,
    "w3m": _LX_w3m,
    "Watcom-1.0": _LX_Watcom_1_0,
    "Widget-Workshop": _LX_Widget_Workshop,
    "WordNet": _LX_WordNet,
    "Wsuipa": _LX_Wsuipa,
    "WTFNMFPL": _LX_WTFNMFPL,
    "WTFPL": _LX_WTFPL,
    "wwl": _LX_wwl,
    "X11": _LX_X11,
    "X11-distribute-modifications-variant": _LX_X11_distribute_modifications_variant,
    "X11-no-permit-persons": _LX_X11_no_permit_persons,
    "X11-swapped": _LX_X11_swapped,
    "Xdebug-1.03": _LX_Xdebug_1_03,
    "Xerox": _LX_Xerox,
    "Xfig": _LX_Xfig,
    "XFree86-1.1": _LX_XFree86_1_1,
    "xinetd": _LX_xinetd,
    "xkeyboard-config-Zinoviev": _LX_xkeyboard_config_Zinoviev,
    "xlock": _LX_xlock,
    "Xnet": _LX_Xnet,
    "xpp": _LX_xpp,
    "XSkat": _LX_XSkat,
    "xzoom": _LX_xzoom,
    "YPL-1.0": _LX_YPL_1_0,
    "YPL-1.1": _LX_YPL_1_1,
    "Zed": _LX_Zed,
    "Zeeff": _LX_Zeeff,
    "Zend-2.0": _LX_Zend_2_0,
    "Zimbra-1.3": _LX_Zimbra_1_3,
    "Zimbra-1.4": _LX_Zimbra_1_4,
    "Zlib": _LX_Zlib,
    "zlib-acknowledgement": _LX_zlib_acknowledgement,
    "ZPL-1.1": _LX_ZPL_1_1,
    "ZPL-2.0": _LX_ZPL_2_0,
    "ZPL-2.1": _LX_ZPL_2_1,
}

export const LICENSE_IDS = Object.keys(licenses).sort()
